import React from 'react'

function TableWeek() {
  return (
    <>
     <p className='text-center text-white h2 my-5'>(Week 45 - from 2022-10-31 to 2022-11-06)</p>
     <div  className='d-flex justify-content-center'>
       
       <table className="table__week" >
      <thead>
        <tr>
          <td>#</td>
          <td>Wallet</td>
          <td>Ganied Respect</td>
        </tr>
      </thead>
      <tbody >
       <tr>
          <td>
              1
          </td>
          <td>
            text.ss
          </td>
          <td>
           5458.7777
          </td>
       </tr>
       <tr>
          <td>
              1
          </td>
          <td>
            text.ss
          </td>
          <td>
           5458.7777
          </td>
       </tr>
       <tr>
          <td>
              1
          </td>
          <td>
            text.ss
          </td>
          <td>
           5458.7777
          </td>
       </tr>
       <tr>
          <td>
              1
          </td>
          <td>
            text.ss
          </td>
          <td>
           5458.7777
          </td>
       </tr>
       <tr>
          <td>
              1
          </td>
          <td>
            text.ss
          </td>
          <td>
           5458.7777
          </td>
       </tr>
       <tr>
          <td>
              1
          </td>
          <td>
            text.ss
          </td>
          <td>
           5458.7777
          </td>
       </tr>
       <tr>
          <td>
              1
          </td>
          <td>
            text.ss
          </td>
          <td>
           5458.7777
          </td>
       </tr>
       <tr>
          <td>
              1
          </td>
          <td>
            text.ss
          </td>
          <td>
           5458.7777
          </td>
       </tr>
       <tr>
          <td>
              1
          </td>
          <td>
            text.ss
          </td>
          <td>
           5458.7777
          </td>
       </tr>
       <tr>
          <td>
              1
          </td>
          <td>
            text.ss
          </td>
          <td>
           5458.7777
          </td>
       </tr>
       <tr>
          <td>
              1
          </td>
          <td>
            text.ss
          </td>
          <td>
           5458.7777
          </td>
       </tr>
       <tr>
          <td>
              1
          </td>
          <td>
            text.ss
          </td>
          <td>
           5458.7777
          </td>
       </tr>
       <tr>
          <td>
              1
          </td>
          <td>
            text.ss
          </td>
          <td>
           5458.7777
          </td>
       </tr>
       <tr>
          <td>
              1
          </td>
          <td>
            text.ss
          </td>
          <td>
           5458.7777
          </td>
       </tr>
       <tr>
          <td>
              1
          </td>
          <td>
            text.ss
          </td>
          <td>
           5458.7777
          </td>
       </tr>
       <tr>
          <td>
              1
          </td>
          <td>
            text.ss
          </td>
          <td>
           5458.7777
          </td>
       </tr>
       <tr>
          <td>
              1
          </td>
          <td>
            text.ss
          </td>
          <td>
           5458.7777
          </td>
       </tr>
       <tr>
          <td>
              1
          </td>
          <td>
            text.ss
          </td>
          <td>
           5458.7777
          </td>
       </tr>
      </tbody>
    </table>
  </div>
    </>
  
  )
}

export default TableWeek